Repository fedotkin/dotnet, pull requests merged in 2022-11, with the labels that each got.

#8 #4 Root folder workarounds
  .gitignore
  ConsoleApp1/.vs/ConsoleApp1/v16/.suo
  ConsoleApp1/bin/Debug/net5.0/ConsoleApp1.dll
  ConsoleApp1/bin/Debug/net5.0/ConsoleApp1.pdb
  ConsoleApp1/obj/Debug/net5.0/ConsoleApp1.dll
  ConsoleApp1/obj/Debug/net5.0/ConsoleApp1.pdb
  README.md
  csharp_logo.png
  dotnet_logo.png
  readme.txt
  trey-nash/05 for the 'Interfaces and Contracts' chapter/README.md
Labels: documentation, master

#11 #9 Create Assets branch | Fix displaying of logo images
  README.md
  csharp_logo.png
  dotnet_logo.png
Labels: enhancement, master

#13 #9 Create Assets branch | Fix displaying of logo images
  README.md
  csharp_logo.png
  dotnet_logo.png
Labels: enhancement

#18 #16 Polish README
  README.md
Labels: master, hotfix
